### ISSUE TITLE
LinterShellcheck.Linter is deprecated.

### ISSUE THREAD

**Issue by ApfelUser** [AtomLinter/linter-bootlint#12] opened 2015-07-21 15:55 UTC
AtomLinter v0.X.Y API has been deprecated. Please refer to the Linter docs to update and the latest API: https://github.com/atom-community/linter/wiki/Migrating-to-the-new-API
```
LinterBootlint.Linter (/Users/apfeluser/.atom/packages/linter/lib/linter.coffee:60:4)
new LinterBootlint (/Users/apfeluser/.atom/packages/linter-bootlint/lib/linter-bootlint.coffee:26:4)
Object.lint (/Users/apfeluser/.atom/packages/linter/lib/legacy.coffee:61:21)
<unknown> (/Users/apfeluser/.atom/packages/linter/lib/editor-linter.coffee:69:25)
currentLinter (/Users/apfeluser/.atom/packages/linter/lib/editor-linter.coffee:68:19)
<unknown> (/Users/apfeluser/.atom/packages/linter/lib/editor-linter.coffee:82:22)
```

**Comment by steelbrain** [comment] 2015-10-14 15:53
This linter provider is no longer maintained. I would love to review a community PR upgrading this.

**Comment by Arcanemagus** [comment] 2015-10-14 17:55
Closing as a duplicate of #11 (although different stack traces the root issue is the same).

**Closed by Arcanemagus** 2015-10-14 17:55 UTC
