### ISSUE TITLE
Object.activate is deprecated.

### ISSUE THREAD

**Issue by skatedude007** [AtomLinter/linter-bootlint#13] opened 2015-09-21 06:28 UTC
AtomLinter legacy API has been removed. Please refer to the Linter docs to update and the latest API: https://github.com/atom-community/linter/wiki/Migrating-to-the-new-API
```
Object.activate (/Users/jashkothari/.atom/packages/linter/lib/main.coffee:78:6)
Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:222:19)
<unknown> (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:203:30)
Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:147:15)
```

**Comment by steelbrain** [comment] 2015-09-21 12:18
This repo is kinda abandoned. We would love to accept a PR for this

**Comment by Arcanemagus** [comment] 2015-10-14 17:54
Closing as a duplicate of #11 (although different stack traces the root issue is the same).

**Closed by Arcanemagus** 2015-10-14 17:54 UTC
